---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability
  namespace: argocd
  finalizers:  # Add a this finalizer ONLY if you want these to cascade delete.
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/aetna-digital-infrastructure/dfp-gitops-stack-observability.git
    targetRevision: HEAD
    path: packages
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  directory:
    recurse: true
  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
